import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

object VerizonNewActivationPages{

	val VZWScanToPaymentOptions = group("${carrier}_Scan"){
		exec(http("dsom_Scan_30")
			.options(Common.uri_dsom + "/session/dsom/v1/cart/item")
			.headers(VerizonNewActivationHeaders.dsom_headers_230))
			.exec(http("dsom_Scan_31")
				.post(Common.uri_dsom + "/session/dsom/v1/cart/item")
				.headers(VerizonNewActivationHeaders.dsom_headers_231)
				.body(ElFileBody("Verizon/NewActivationE2E/VZW_0031_request.json")))
			.exec(http("dsom_Scan_32")
				.options(Common.uri_dsom + "/dsom-app/v1/getNextState")
				.headers(VerizonNewActivationHeaders.dsom_headers_222))
			.exec(http("dsom_Scan_33")
				.post(Common.uri_dsom + "/dsom-app/v1/getNextState")
				.check(regex("\"cartCount\":1").find.exists)
				.headers(VerizonNewActivationHeaders.headers_223)
				.body(ElFileBody("Verizon/NewActivationE2E/VZW_0033_request.json")))
			.pause(1)
			.exec(http("dsom_Scan_34")
				.options(Common.uri_dsom + "/dsom-app/v1/getContentForAisle")
				.headers(VerizonNewActivationHeaders.dsom_headers_222))
			.exec(http("dsom_Scan_35")
				.post(Common.uri_dsom + "/dsom-app/v1/getContentForAisle")
				.headers(VerizonNewActivationHeaders.headers_223)
				.body(ElFileBody("Verizon/NewActivationE2E/VZW_0035_request.json")))
			.exec(http("dsom_Scan_36_payment_options_html")
				.get(Common.uri_ui + "/app/pages/paymentoptions/paymentoptions.html")
				.headers(VerizonNewActivationHeaders.ui_headers_6))
			.exec(http("dsom_Scan_36")
				.options(Common.uri_dsom + "/dsom-app/v1/getPaymentDetails")
				.headers(VerizonNewActivationHeaders.dsom_headers_222))
			.exec(http("dsom_Scan_37")
				.post(Common.uri_dsom + "/dsom-app/v1/getPaymentDetails")
				.check(regex("paymentOptions").find.exists)
				.check(substring("Get more savings with Device Payment on The Verizon Plan"))
				.headers(VerizonNewActivationHeaders.headers_223)
				.body(ElFileBody("Verizon/NewActivationE2E/VZW_0037_request.json")))
	}

	val CC=group("CreditCheck"){
		exec(http("CC_0")
			.post("/retail/creditcheck/creditcheck.htm")
			.headers(VerizonNewActivationHeaders.VZW_CC_Headers_0)
			.formParam("creditCheckToolArray[1008][newOrExisting]", "new")
			.formParam("creditCheckToolArray[1008][addLineType]", "addNewPlan")
			.formParam("currentPageCOPId", "439")
			.formParam("secretSubmit", "")
			.formParam("creditCheckTool", "1")
			.formParam("edit", "")
			.formParam("Lines_To_Be_Activated", "1")
			.formParam("creditCheckToolArray[1008][numOfNewLines]", "1")
			.formParam("creditCheckToolArray[1008][numOfExistingLines]", "")
			.formParam("Billing_Address_Radio", "unfinished")
			.formParam("Ecom_BillTo_Postal_Name_First", "Fred")
			.formParam("Ecom_BillTo_Postal_Name_Middle", "")
			.formParam("Ecom_BillTo_Postal_Name_Last", "${Lname}")
			.formParam("Ecom_BillTo_Postal_Street_Line1", "536 Banks")
			.formParam("Ecom_BillTo_Postal_Street_Line2", "RAMBLAS")
			.formParam("Ecom_BillTo_Postal_City", "San Francisco")
			.formParam("Ecom_BillTo_Postal_StateProv", "CA")
			.formParam("Ecom_BillTo_Postal_PostalCode", "94117")
			.formParam("Ecom_BillTo_Telecom_Phone_Number", "2342342345")
			.formParam("Ecom_BillTo_Online_Email", "nobody@letstalk.com")
			.formParam("Date_of_Birth[1]", "02")
			.formParam("Date_of_Birth[2]", "20")
			.formParam("Date_of_Birth[3]", "1970")
			.formParam("Social_Security", "${SSN1}${SSN2}${SSN3}${SSN4}")
			.formParam("Identification_Type", "licns")
			.formParam("Identification_State", "CA")
			.formParam("Identification_Number", "123456789")
			.formParam("Identification_Expiration_Month", "12")
			.formParam("Identification_Expiration_Year", "2020")
			.formParam("Drivers_license_Checkbox", "Y")
			.formParam("Agree_To_Credit_Check", "Y")
			.formParam("Agree_To_Credit_Check_Hidden", "Y")
			.formParam("checkoutSubmitType", "continue"))
			.exec(http("CC_1")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_1))
			.exec(http("CC_2")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_2))
			.exec(http("CC_3")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_2))
			//.pause(106 milliseconds)
			.exec(http("CC_4")
			.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1490215046074")
			.headers(VerizonNewActivationHeaders.VZW_CC_Headers_4))
			.exec(http("CC_5")
				.get("/retail/creditcheck/controller/runprecreditcheck.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_5))
			.exec(http("CC_6")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_1))
			.exec(http("CC_7")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_2))
			.exec(http("CC_8")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_2))
			//.pause(111 milliseconds)
			.exec(http("CC_9")
			.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1490215055419")
			.headers(VerizonNewActivationHeaders.VZW_CC_Headers_4))
			.exec(http("CC_10")
				.get("/retail/creditcheck/controller/runprecreditcheck.php")
				.check(substring("Carrier credit check successful. Continue with Verizon Wireless"))
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_5))
			.exec(http("CC_11")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_11))
			.exec(http("CC_12")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_12))
			.exec(http("CC_13")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZW_CC_Headers_12))
			//.pause(135 milliseconds)
			.exec(http("CC_14")
			.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1490215057302")
			.headers(VerizonNewActivationHeaders.VZW_CC_Headers_14))
	}

	val CreditCheck=group("CreditCheck"){
		exec(http("dsom_CreditCheck_0")
			.options(Common.uri_dsom_v1_port + "/getNextState")
			.headers(VerizonNewActivationHeaders.dsom_headers_222))
			.pause(30)
			.exec(http("dsom_CreditCheck_1_post_form")
				.post(Common.uri_dsom_v1_port + "/getNextState")
				.check(regex("Error retrieving the next state for").find.notExists)
				.headers(VerizonNewActivationHeaders.dsom_headers_1)
				.body(ElFileBody("Verizon/NewActivationE2E/CreditCheckToIDP_0001_request.json")))
			.pause(40)
			.exec(http("dsom_CreditCheck_2_process_php")
				.get(Common.uri_poa_no_port + "/retail/orderassembly/controller/process.php")
				.headers(VerizonNewActivationHeaders.poa_headers_2)
				.resources(http("dsom_CreditCheck_3")
					.get(Common.uri_ui + "/assets/img/cloader.gif"),
					http("ui_cc_request_8")
						.get(Common.uri_ui + "/config.json")
						.headers(VerizonNewActivationHeaders.ui_headers_8)))
			.pause(5)
			.exec(http("dsom_CreditCheck_9")
				.options(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.dsom_headers_230))
			.pause(5)
			.exec(http("dsom_CreditCheck_10")
				.post(Common.uri_dsom_v1_port + "/getNextState")
				.check(regex("Error retrieving the next state for").find.notExists)
				.headers(VerizonNewActivationHeaders.dsom_headers_231)
				.body(ElFileBody("Verizon/NewActivationE2E/CreditCheckToIDP_0010_request.json")))
			.pause(5)
			.exec(http("dsom_CreditCheck_11")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.dsom_headers_231)
				.body(ElFileBody("Verizon/NewActivationE2E/CreditCheckToIDP_0011_request.json")))
			.pause(5)
			.exec(http("dsom_CreditCheck_12")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.check(regex("Installment Details").find.exists)
				.headers(VerizonNewActivationHeaders.dsom_headers_231)
				.body(ElFileBody("Verizon/NewActivationE2E/CreditCheckToIDP_0012_request.json"))
				.resources(
					//http("ui_cc_request_13")
					//	.get(Common.uri_ui + "/shopping/build/ch_9afac72ed1aa9ce2cabc_min.js")
					http("ui_cc_request_14")
						.get(Common.uri_ui + "/app/pages/frame/header/header.html")
						.headers(VerizonNewActivationHeaders.ui_headers_6),
					http("ui_cc_request_15")
						.get(Common.uri_ui + "/app/pages/frame/footer/footer.html")
						.headers(VerizonNewActivationHeaders.ui_headers_6),
					http("ui_cc_request_16")
						.get(Common.uri_ui + "/app/pages/installmentdetails/installmentdetails.html")
						.headers(VerizonNewActivationHeaders.ui_headers_16)))
			//	.pause(74)
			.exec(http("ui_cc_request_17")
			.get(Common.uri_ui + "/assets/img/bullseye.svg")
			.resources(http("uri_request_18")
				.get(Common.uri_ui + "/app/components/channel/channel.html")
				.headers(VerizonNewActivationHeaders.ui_headers_16)))
			.pause(4)
			.exec(http("dsom_creditcheck_19")
				.options(Common.uri_dsom_v1_port + "/paymentPlans")
				.headers(VerizonNewActivationHeaders.dsom_headers_19))
			.pause(4)
			.exec(http("dsom_creditcheck_20")
				.get(Common.uri_dsom_v1_port + "/paymentPlans")
				.headers(VerizonNewActivationHeaders.dsom_headers_20))
			.exec(http("dsom_creditcheck_21")
				.get(Common.uri_poa_no_port + "/img/prod/cell-phones/verizonwireless/samsung/samsung-galaxy-s7-edge-black_front_med.png")
				.headers(VerizonNewActivationHeaders.poa_headers_2))

	}

	val CC2IDP=group("${carrier}_CreditCheck_IDP"){
		exec(http("CreditCheck_IDP_27")
			.post("/retail/creditcheck/result.htm")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_1027)
			.formParam("submitType", "continue")
			.formParam("acceptCorp", "660")
			.formParam("acceptType", "passed")
			.formParam("secondRun", "")
			.formParam("numofline_to_activate", "1")
			.formParam("checkbox-1", "on"))
			.exec(http("CreditCheck_IDP_28")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_101)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWPO2Activation_0028_request.json")))
			.exec(http("CreditCheck_IDP_29")
				.options(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1000))
			.exec(http("CreditCheck_IDP_30")
				.post(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_101)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWPO2Activation_0030_request.json")))
			.exec(http("CreditCheck_IDP_31")
				.options(Common.uri_dsom_v1_port + "/getJSONAisles")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1000))
			.exec(http("CreditCheck_IDP_32")
				.post(Common.uri_dsom_v1_port + "/getJSONAisles")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_101)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWPO2Activation_0032_request.json")))
			.exec(http("CreditCheck_IDP_33")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.check(substring("Sales tax based on full"))
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_101)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWPO2Activation_0033_request.json")))
			.pause(144 milliseconds)
			.exec(http("CreditCheck_IDP_34")
				.options(Common.uri_dsom_v1_port + "/paymentPlans")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1034))
			.exec(http("CreditCheck_IDP_35")
				.get(Common.uri_dsom_v1_port + "/paymentPlans")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1035))
		//.pause(5, 15)
	}

	val IDP2PlanInCC=group("${carrier}_IDP_Plan"){
		exec(http("IDP_Plan36")
			.options(Common.uri_dsom + "/session/dsom/v1/cart/item/1")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_1036))
			.exec(http("IDP_Plan37")
				.patch(Common.uri_dsom + "/session/dsom/v1/cart/item/1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1037)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWPO2Activation_0037_request.json")))
			.exec(http("IDP_Plan38")
				.options(Common.uri_dsom + "/dsom-app/v1/getNextState")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1000))
			.exec(http("IDP_Plan39")
				.post(Common.uri_dsom + "/dsom-app/v1/getNextState")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_101)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWPO2Activation_003_request.json")))
			.exec(http("IDP_Plan40")
				.get("/retail/orderassembly/controller/process.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_106))
			//.exec(http("IDP_Plan41")
			//		.get(Common.uri_ui + "/build/css_17b781d9571d1352024a_min.js"))
			//.exec(http("IDP_Plan42")
			//		.get(Common.uri_ui + "/build/bundle_17b781d9571d1352024a_min.js"))
			.exec(http("IDP_Plan43")
			.options(Common.uri_dsom_v1_port + "/getContentForAisle")
			.headers(VerizonNewActivationHeaders.dsom_headers_222))
			.exec(http("IDP_Plan44")
				.post(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.dsom_headers_231)
				.body(ElFileBody("Verizon/NewActivationE2E/IDPToPlans_015_request.json")))
			.exec(http("IDP_Plan45")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.dsom_headers_1)
				.body(ElFileBody("Verizon/NewActivationE2E/IDPToPlans_016_request.json")))
			.exec(http("request_27")
				.options(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.dsom_headers_222))
			.exec(http("request_28")
				.post(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.dsom_headers_1)
				.body(ElFileBody("Verizon/NewActivationE2E/PlansToFeatures_0028_request.json"))
				.resources(
					http("IDP_Planrequest_18")
						.get(Common.uri_ui + "/app/pages/frame/header/header.html"),
					http("IDP_Planrequest_19")
						.get(Common.uri_ui + "/app/pages/frame/footer/footer.html"),
					http("IDP_Planrequest_20")
						.get(Common.uri_ui + "/app/pages/selectproduct/selectservice.html"),
					http("IDP_Planrequest_21")
						.get(Common.uri_ui + "/assets/img/bullseye.svg"),
					http("IDP_Planrequest_22")
						.get(Common.uri_ui + "/app/components/contempiler/config.json"),
					http("IDP_Planrequest_23")
						.get(Common.uri_ui + "/app/components/contempiler/contempiler.html"),
					http("IDP_Planrequest_24")
						.get("/img/retail/corps/plLgs660.png"),
					http("IDP_Planrequest_25")
						.get(Common.uri_ui + "/app/components/contempiler/contemloader.html"),
					http("IDP_Planrequest_26")
						.get(Common.uri_ui + "/app/components/contempiler/sets/carrierinfo/verizon_hide.html")))
	}

	val IDP2Plan=group("${carrier}_IDP_Plan"){
		exec(http("IDP_Plan36")
			.options(Common.uri_dsom + "/session/dsom/v1/cart/item/1")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_1036))
			.exec(http("IDP_Plan37")
				.patch(Common.uri_dsom + "/session/dsom/v1/cart/item/1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1037)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWPO2Activation_0037_request.json")))
			.exec(http("IDP_Plan38")
				.options(Common.uri_dsom + "/dsom-app/v1/getNextState")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1000))
			.exec(http("IDP_Plan39")
				.post(Common.uri_dsom + "/dsom-app/v1/getNextState")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_101)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWPO2Activation_0039_request.json")))
			.exec(http("IDP_Plan40")
				.get("/retail/orderassembly/controller/process.php")
				.check(substring("Pick the perfect plan to stay connected wherever you"))
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_106))
			.exec(http("IDP_Plan41")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1041))
			.exec(http("IDP_Plan42")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1042))
			.exec(http("IDP_Plan43")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1042))
			.exec(http("IDP_Plan44")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489019148728")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1044))
		////.pause(10, 15)
	}

	val SelectPlan=group("SelectPlan"){
		exec(http("SelectPlan_45")
			.get("/retail/orderassembly/controller/process.php?addServicePrIds=42340")
			.check(substring("Your Cart"))
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_1045))
			.exec(http("SelectPlan_46")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1046))
			.exec(http("SelectPlan_47")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1047))
			.exec(http("SelectPlan_48")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1047))
			.exec(http("SelectPlan_49")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489019193820")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1049))
		//.pause(5, 15)
	}

	val YourCart=group("YourCart"){
		exec(http("YourCart_50")
			.post("/retail/orderassembly/cart.htm")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_1050)
			.formParam("action", "continue")
			.formParam("continueOnConfirm", ""))
			.exec(http("YourCart_51")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1051))
			.exec(http("YourCart_52")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1052))
			.exec(http("YourCart_53")
				.get("/js/track.php?pageTag=$pageTag")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1052))
			.exec(http("YourCart_54")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1052))
			.exec(http("YourCart_55")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489019212493")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_1055))
	}

	val SelectPlanFeaturesInCC=group("${carrier}_SelectPlanFeatures"){
		exec(http("SelectPlanFeatures_10")
			.get(Common.uri_ui + "/assets/img/cloader.gif"))
			.exec(http("featuresrequest_64")
				.get(Common.uri_ui + "/config.json")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_4))
			.exec(http("featuresrequest_65")
				.options(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_70))
			.exec(http("featuresrequest_66")
				.options(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.ui_headers_70))
			.exec(http("featuresrequest_67")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/PlansToFeatures_0067_request.json")))
			.exec(http("featuresrequest_68")
				.post(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/PlansToFeatures_0068_request.json")))
			.pause(1)
			.exec(http("featuresrequest_69")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/PlansToFeatures_0069_request.json"))
				.resources(http("featuresrequest_71")
					.get(Common.uri_ui + "/app/pages/frame/header/header.html")
					.headers(VerizonNewActivationHeaders.ui_headers_72),
					http("featuresrequest_72")
						.get(Common.uri_ui + "/app/pages/frame/footer/footer.html")
						.headers(VerizonNewActivationHeaders.ui_headers_72),
					http("featuresrequest_73")
						.get(Common.uri_ui + "/app/pages/addons/serviceaddon.html")
						.headers(VerizonNewActivationHeaders.ui_headers_72),
					http("featuresrequest_74")
						.get(Common.uri_ui + "/assets/img/bullseye.svg"),
					http("featuresrequest_75")
						.get("/img/prod/cell-phones/verizonwireless/samsung/samsung-galaxy-s7-edge-black_front_med.png")
						.headers(VerizonNewActivationHeaders.ui_headers_72)))
			.pause(3)
			.exec(http("featuresrequest_76")
				.post(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/PlansToFeatures_0076_request.json")))
			.pause(1)
			.exec(http("featuresrequest_77")
				.get("/retail/orderassembly/controller/process.php")
				.headers(VerizonNewActivationHeaders.poa_headers_2)
				.resources(
					http("featuresrequest_84")
						.get(Common.uri_ui + "/assets/img/cloader.gif")))
	}

	val SelectPlanFeatures=group("${carrier}_SelectPlanFeatures"){
		exec(http("SelectPlanFeatures_10")
			.post("/retail/orderassembly/features.htm")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_10)
			.formParam("posted", "1")
			.formParam("addPurchaseOptionsArr[1][42340][185]", "1")
			.formParam("shownPoptIds[99401]", "99401")
			.formParam("shownPoptIds[99518]", "99518"))
			.exec(http("SelectPlanFeatures_11")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_11))
			.exec(http("SelectPlanFeatures_12")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_12))
			.exec(http("SelectPlanFeatures_13")
				.get("/js/track.php?pageTag=RTLDO")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_12))
			.exec(http("SelectPlanFeatures_14")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_12))
			.exec(http("SelectPlanFeatures_15")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489604767762")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_15))
		//.pause(5, 15)
	}

	val SelectProtectionPlanInCC=group("${carrier}_SelectProtectionPlanCC"){
		exec(http("SelectProtectionPlan16")
			.get(Common.uri_ui + "/config.json")
			.headers(VerizonNewActivationHeaders.ui_headers_8))
			.exec(http("request_70")
				.options(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_70))
			.exec(http("request_71")
				.options(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.ui_headers_70))
			.exec(http("request_72")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/miniCart_002_request.json")))
			.exec(http("request_73")
				.post(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/miniCart_003_request.json")))
			.pause(1)
			.exec(http("dsom_post_insurance_74")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/miniCart_004_request.json")))
			.exec(http("request_75")
				.get(Common.uri_ui + "/app/pages/addons/device.html")
				.headers(VerizonNewActivationHeaders.ui_headers_16)
				.resources(http("request_76")
					.get(Common.uri_ui + "/app/pages/frame/header/header.html")
					.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_77")
						.get(Common.uri_ui + "/app/pages/frame/footer/footer.html")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_79")
						.get(Common.uri_ui + "/assets/img/bullseye.svg"),
					http("request_80")
						.get(Common.uri_ui + "/app/components/showhide/showhide.html")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_81")
						.get(Common.uri_ui + "/app/components/productoptions/partials/productchoices.html")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_82")
						.options(Common.uri_dsom_v1_port + "/getAddOnOptions")
						.headers(VerizonNewActivationHeaders.ui_headers_70),
					http("request_83")
						.get(Common.uri_ui + "/app/components/contempiler/config.json")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_84")
						.get(Common.uri_ui + "/app/components/contempiler/contempiler.html")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_85")
						.post(Common.uri_dsom_v1_port + "/getAddOnOptions")
						.headers(VerizonNewActivationHeaders.ui_headers_72)
						.body(ElFileBody("Verizon/NewActivationE2E/miniCart_005_request.json")),
					http("request_86")
						.get(Common.uri_ui + "/app/components/contempiler/contemloader.html")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_87")
						.get(Common.uri_ui + "/app/components/selectioninputs/partials/choices.html")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_88")
						.get(Common.uri_ui + "/app/components/contempiler/sets/blurb/squaretrade.json")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_89")
						.get(Common.uri_ui + "/app/components/contempiler/sets/blurb/default.html")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_90")
						.get("/img/prod/cell-phones/verizonwireless/samsung/samsung-galaxy-s7-edge-black_front_med.png")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_91")
						.get(Common.uri_ui + "/assets/img/squaretrade_logo_325x160.png")
						.headers(VerizonNewActivationHeaders.ui_headers_16)))
			.pause(4)

			//part 2 of selection protection plan - transition from DSOM to legacy number port
			.exec(http("dsom_switch_to_legacy_numberport_92")
			.options(Common.uri_dsom + "/session/dsom/v1/cart/item")
			.headers(VerizonNewActivationHeaders.ui_headers_70))
			.exec(http("request_93")
				.post(Common.uri_dsom + "/session/dsom/v1/cart/item")
				.headers(VerizonNewActivationHeaders.dsom_headers_231)
				.body(ElFileBody("Verizon/NewActivationE2E/CartItem_patch_003_request.json")))
			.exec(http("request_94")
				.post(Common.uri_dsom_v1_port + "/getNextState")
				.headers(VerizonNewActivationHeaders.dsom_headers_1)
				.body(ElFileBody("Verizon/NewActivationE2E/CartItem_patch_004_request.json")))
			.pause(1)
			.exec(http("request_95")
				.get("/retail/orderassembly/controller/process.php")
				.headers(VerizonNewActivationHeaders.poa_headers_2))
			.pause(1)
			.exec(http("request_96")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_01)
				.resources(http("request_97")
					.get("/jslibs/jquery.php?ver=1.8.2"),
					http("request_98")
						.get("/jslibs/modernizr.php")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_99")
						.get("/jslibs/jquerymobile.php")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_100")
						.get("/template/public/styles/new.main.css")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_101")
						.get("/template/css/semantic.jqmsafe.min.css")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_102")
						.get("/retail/public/styles/main.css")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_103")
						.get("/js/retail/topnav.php")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_104")
						.get("/retail/public/styles/jquery.mobile-1.2.0.css")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_105")
						.get("/brands/target/retail/public/styles/jquery.mobile-1.2.0.css")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_106")
						.get("/brands/target/retail/public/styles/main.css")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_107")
						.get("/js/retail/checkoutinit.js")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_108")
						.get("/js/datechange.js")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("request_109")
						.get("/js/retail/numport.php?devices=%7B%221%22%3A%7B%22device%22%3A%7B%2242252%22%3A42252%7D%2C%22service%22%3A%7B%2242340%22%3A42340%7D%7D%7D")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_110")
						.get("/img/retail/ajax-loader.gif")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_111")
						.get("/img/brands/target/retail/logo-mini.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_112")
						.get("/retail/public/img/alertsprite.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_113")
						.get("/retail/public/img/reservesprite.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_114")
						.get("/img/retail/cart.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_115")
						.get("/img/retail/setting.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_116")
						.get("/img/retail/icons-18-white.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_117")
						.get("/img/retail/home.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_118")
						.get("/img/retail/inventory-management.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_119")
						.get("/img/retail/customer-lookup.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_120")
						.get("/img/retail/save.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_121")
						.get("/img/retail/lock.png")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_01),
					http("request_122")
						.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1504646577165")
						.headers(VerizonNewActivationHeaders.VZWFlowheaders_4)))
		//.pause(5, 15)
	}

	val SelectProtectionPlan=group("${carrier}_SelectProtectionPlan"){
		exec(http("SelectProtectionPlan16")
			.get("/minicart/minicart.php?type=popt&isNoResponse=1&noCache=0.5845231551502829&action=update&dataArray%5Badd%5D%5BaddPoptId%5D=99485&dataArray%5Badd%5D%5BaddPoptIdIndex%5D=1")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_16))
			.exec(http("SelectProtectionPlan17")
				.post("/retail/orderassembly/controller/process.php?action=featureAdded")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_17)
				.formParam("isNoResponse", "1")
				.formParam("doNotRequest", "0")
				.formParam("isNoInsuranceSelected", "0")
				.formParam("addPurchaseOptionsArr[1][42252][259]", "1")
				.formParam("shownPoptIds[99485]", "99485")
				.formParam("guestReview", "on")
				.formParam("continueButton", "continue"))
			.exec(http("SelectProtectionPlan18")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_18))
			.exec(http("SelectProtectionPlan19")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_19))
			.exec(http("SelectProtectionPlan20")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_19))
			.exec(http("SelectProtectionPlan21")
				.get("/js/retail/numport.php?devices=%7B%221%22%3A%7B%22device%22%3A%7B%2242252%22%3A42252%7D%2C%22service%22%3A%7B%2242340%22%3A42340%7D%7D%7D")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_19))
			.exec(http("SelectProtectionPlan22")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489604798563")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_22))
		//.pause(5, 15)
	}

	val NumberPort=group("${carrier}_NumberPort"){
		exec(http("NumberPort_23")
			.post("/retail/checkout/checkout.htm?copId=436")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_23)
			.formParam("currentPageCOPId", "436")
			.formParam("secretSubmit", "")
			.formParam("creditCheckTool", "")
			.formParam("edit", "")
			.formParam("Number_Port_Radio", "N")
			.formParam("checkoutSubmitType", "continue"))
			.exec(http("NumberPort_24")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_24))
			.exec(http("NumberPort_25")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_25))
			.exec(http("NumberPort_26")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_25))
			.exec(http("NumberPort_27")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489604817061")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_27))
		//.pause(5, 18)
	}

	val OrderReviewandConfirm=group("${carrier}_OrderReviewandConfirm"){
		exec(http("OrderReveviewandConfirm_28")
			.get("/retail/checkout/termsconditions.htm")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_28))
			.exec(http("OrderReveviewandConfirm_29")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_29))
			.exec(http("OrderReveviewandConfirm_30")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_30))
			.exec(http("OrderReveviewandConfirm_31")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_30))
			////.pause(140 milliseconds)
			.exec(http("OrderReveviewandConfirm_32")
			.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489604837215")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_32))
		//.pause(5, 15)
	}

	val TermsandConditions=group("${carrier}_TermsandConditions"){
		exec(http("TermsandConditions_33")
			.post("/retail/checkout/termsconditions.htm")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_33)
			.formParam("termsConditions[lt]", "Y"))
			.exec(http("TermsandConditions_34")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_34))
			.exec(http("TermsandConditions_35")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_35))
			.exec(http("TermsandConditions_36")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_35))
			.exec(http("TermsandConditions_37")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489604863565")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_37))
			.exec(http("TermsandConditions_38")
				.get("/retail/rtcc/runcreditprocess.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_38))
			.exec(http("TermsandConditions_39")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_39))
			.exec(http("TermsandConditions_40")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_40))
			.exec(http("TermsandConditions_41")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_40))
			.exec(http("TermsandConditions_42")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489604874466")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_42))
			.exec(http("TermsandConditions_43")
				.get("/js/retail/getnotifications.php?reqType=getreservationcount&cacheVar=1489604874544&storeId=0003")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_42))
		//.pause(5, 15)
	}

	val SwipeCard=group("${carrier}_SwipeCard"){
		exec(http("SwipeCard_44")
			.post("/ajax/retail/savebillingaddress.php")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_44)
			.formParam("addressChoice", "same")
			.formParam("Billing_Address_Radio", "Y")
			.formParam("Ecom_BillTo_Postal_Name_First", "Fred")
			.formParam("Ecom_BillTo_Postal_Name_Middle", "")
			.formParam("Ecom_BillTo_Postal_Name_Last", "Consumer Two")
			.formParam("Ecom_BillTo_Postal_Street_Line1", "536 Banks St")
			.formParam("Ecom_BillTo_Postal_Street_Line2", "CRAPOLA")
			.formParam("Ecom_BillTo_Postal_City", "San Francisco")
			.formParam("Ecom_BillTo_Postal_StateProv", "CA")
			.formParam("Ecom_BillTo_Postal_PostalCode", "94117"))
			.pause(15)
			.exec(http("SwipeCard_45")
				.get("/ajax/retail/auruscallbackresponse.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_42))
			.exec(http("SwipeCard_46")
				.post("/retail/checkout/emvpayment.htm")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_46)
				.formParam("addressChoice", "same")
				.formParam("Billing_Address_Radio", "Y")
				.formParam("Ecom_BillTo_Postal_Name_First", "Fred")
				.formParam("Ecom_BillTo_Postal_Name_Middle", "")
				.formParam("Ecom_BillTo_Postal_Name_Last", "Consumer Two")
				.formParam("Ecom_BillTo_Postal_Street_Line1", "536 Banks St")
				.formParam("Ecom_BillTo_Postal_Street_Line2", "CRAPOLA")
				.formParam("Ecom_BillTo_Postal_City", "San Francisco")
				.formParam("Ecom_BillTo_Postal_StateProv", "CA")
				.formParam("Ecom_BillTo_Postal_PostalCode", "94117"))
			.exec(http("SwipeCard_47")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_47))
			.exec(http("SwipeCard_48")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_48))
			.exec(http("SwipeCard_49")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_48))
			.exec(http("SwipeCard_50")
				.get("/barcode.htm?code=15/25504056500799990000001890&width=360&height=90&type=C128B&font=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_50))
			.exec(http("SwipeCard_51")
				.get("/barcode.htm?code=9881257290057620&height=90&type=C128B&font=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_50))
			//.pause(125 milliseconds)
			.exec(http("SwipeCard_52")
			.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489604920754")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_52))
		//.pause(5, 15)
	}

	val PrintMobileScanSheet=group("${carrier}_PrintMobileScanSheet"){
		exec(http("PrintMobileScanSheet_53")
			.get("/retail/controller/saleassocflowcontroller.php?activate=1")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_53))
			.exec(http("PrintMobileScanSheet_54")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_54))
			.exec(http("PrintMobileScanSheet_55")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_55))
			.exec(http("PrintMobileScanSheet_56")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_55))
			.exec(http("PrintMobileScanSheet_57")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489604944366")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_57))
		//.pause(5, 14)
	}

	val ScanReceipt=group("${carrier}_ScanReceipt"){
		exec(http("ScanReceipt_58")
			.post("/ajax/retail/fakereceipt.php")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_58))
			.exec(http("ScanReceipt_59")
				.post("/retail/receiptscan.htm")
				//			.check(regex("Activation for order: #(.+?)</h3>").saveAs("p_orderid"))
				.check(regex("Activation for order: #(.+?)</h3>").saveAs("p_orderid"))

				.headers(VerizonNewActivationHeaders.VZWFlowheaders_59)
				.formParam("receiptId", "485945645720265173"))
			.exec(http("ScanReceipt")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_60))
			.exec(http("ScanReceipt_61")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_61))
			.exec(http("ScanReceipt_62")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_61))
			.exec(http("ScanReceipt_63")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489604964706")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_63))
		//.pause(5, 15)
	}

	val EnterIMEIandSIM=group("${carrier}_EnterIMEIandSIM"){
		exec(http("EnterIMEIandSIM64")
			.post("/retail/checkout/activationscan.htm")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_64)
			.formParam("serial", "")
			.formParam("device[99000088304056]", "Y")
			.formParam("deviceScanInfo[${p_orderid}_42252_1_1][sim]", "99999999998888888888"))
			.exec(http("EnterIMEIandSIM65")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_65))
			.exec(http("EnterIMEIandSIM66")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_66))
			.exec(http("EnterIMEIandSIM67")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_66))
			.exec(http("EnterIMEIandSIM68")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489605011210")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_68))
			.exec(http("EnterIMEIandSIM69")
				.get("/js/retail/getnotifications.php?reqType=getreservationcount&cacheVar=1489605011317&storeId=0003")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_68))
			.exec(http("EnterIMEIandSIM70")
				.get("/retail/controller/saleassocflowcontroller.php?parking=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_38))
			.exec(http("EnterIMEIandSIM71")
				.get("/retail/public/styles/normalize.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_65))
			.exec(http("EnterIMEIandSIM72")
				.get("/jslibs/modernizr.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_66))
			.exec(http("EnterIMEIandSIM73")
				.get("/js/retail/topnav.php")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_66))
			.exec(http("EnterIMEIandSIM74")
				.get("/js/retail/getactivealerts.php?reqType=getactivealerts&cacheVar=1489605014629")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_68))
			.exec(http("EnterIMEIandSIM75")
				.get("/js/retail/getnotifications.php?reqType=getreservationcount&cacheVar=1489605014697&storeId=0003")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_68))
			.exec(http("EnterIMEIandSIM76")
				.get("/retail/controller/saleassocflowcontroller.php?parking=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_38))
			.exec(http("EnterIMEIandSIM77")
				.post("/webservices/external/poa_rest/index.php/sales/v1/order")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_77)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWFlow_0077_request.json")))
			.exec(http("EnterIMEIandSIM78")
				.get("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_78))
			.exec(http("EnterIMEIandSIM79")
				.get("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}/contracts")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_78))
			.exec(http("EnterIMEIandSIM80")
				.get("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}/status")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_78))
			.exec(http("EnterIMEIandSIM81")
				.get("/legacy/v1/index.php/strings?pageTags=%5B%22WCAGR%22%5D")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_78))
			.exec(http("EnterIMEIandSIM82")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=c23599627c00cb8a&code=wca&page=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_82))
			.exec(http("EnterIMEIandSIM83")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=c23599627c00cb8a&code=wca&page=2")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_82))
		//.pause(5, 15)
	}

	val WirelessCustomerAgreement=group("${carrier}_WirelessCustomerAgreement"){
		exec(http("WirelessCustomerAgreement")
			.get("/legacy/v1/index.php/strings?pageTags=%5B%22RTLTC%22%5D")
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_78))
			.exec(http("WirelessCustomerAgreement_85")
				.get("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}/productimage")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_78))
			.exec(http("WirelessCustomerAgreement_86")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=c23599627c00cb8a&code=finance&page=4&ordiIndex=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_82))
			.exec(http("WirelessCustomerAgreement_87")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=c23599627c00cb8a&code=finance&page=3&ordiIndex=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_82))
			.exec(http("WirelessCustomerAgreement_88")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=c23599627c00cb8a&code=finance&page=2&ordiIndex=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_82))
			.exec(http("WirelessCustomerAgreement_89")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=c23599627c00cb8a&code=finance&page=1&ordiIndex=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_82))
	}

	val DeviceFinancingInstallmentContract=group("${carrier}_DeviceFinancingInstallmentContract"){
		exec(http("DeviceFinancingInstallmentContract_90")
			.get("/legacy/v1/index.php/strings?pageTags=%5B%22RTLRC%22%5D")
			.check(substring("Order and Activation Complete"))
			.headers(VerizonNewActivationHeaders.VZWFlowheaders_78))
			.exec(http("DeviceFinancingInstallmentContract_91")
				.post("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}/signatures")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_77)
				.body(ElFileBody("Verizon/NewActivationE2E/VZWFlow_0091_request.json")))
			.exec(http("DeviceFinancingInstallmentContract_92")
				.get("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}/status")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_78))
			.exec(http("DeviceFinancingInstallmentContract_93")
				.get("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_78))
			.exec(http("DeviceFinancingInstallmentContract_94")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=c23599627c00cb8a&code=summary&page=1")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_82))
			.exec(http("DeviceFinancingInstallmentContract_95")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=c23599627c00cb8a&code=summary&page=2")
				.headers(VerizonNewActivationHeaders.VZWFlowheaders_82))
	}

	val WarrantyPaymentCapture=group("${carrier}_WarrantyPaymentCapture") {
		exec(http("poa_request_181")
			.get("/legacy/v1/index.php/strings?pageTags=%5B%22RTLTC%22%5D")
			.headers(VerizonNewActivationHeaders.poa_headers_2))
			.exec(http("poa_request_182")
				.get("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}/productimage")
				.headers(VerizonNewActivationHeaders.poa_headers_175))
			.exec(http("poa_request_183")
				.get("/img/prod/cell-phones/verizonwireless/samsung/samsung-galaxy-s7-edge-black_front_med.png"))
			.exec(http("poa_request_184")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=91abe108fe3020fa&code=finance&page=1&ordiIndex=1")
				.headers(VerizonNewActivationHeaders.poa_headers_37))
			.exec(http("poa_request_185")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=91abe108fe3020fa&code=finance&page=2&ordiIndex=1")
				.headers(VerizonNewActivationHeaders.poa_headers_37))
			.exec(http("poa_request_186")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=91abe108fe3020fa&code=finance&page=3&ordiIndex=1")
				.headers(VerizonNewActivationHeaders.poa_headers_37))
			.exec(http("poa_request_187")
				.get("/webservices/external/poa_rest/poa_rest_stream.php?ordId=91abe108fe3020fa&code=finance&page=4&ordiIndex=1")
				.headers(VerizonNewActivationHeaders.poa_headers_37))
			.pause(1)
			.exec(http("poa_request_188")
				.get("/legacy/v1/index.php/strings?pageTags=%5B%22RTLRC%22%5D")
				.headers(VerizonNewActivationHeaders.poa_headers_175)
				.resources(http("poa_request_189")
					.post("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}/signatures")
					.headers(VerizonNewActivationHeaders.VZWFlowheaders_77)
					.body(ElFileBody("Verizon/NewActivationE2E/ActivationsWithInsurance_0189_request.json")),
					http("poa_request_190")
						.get("/img/brands/target/retail/printed-logo.png")))
			.pause(1)
			.exec(http("poa_request_191")
				.get("/webservices/external/poa_rest/index.php/sales/v1/order/${p_orderid}/status"))
			.exec(http("ui_request_192")
				.get(Common.uri_ui + "/")
				.headers(VerizonNewActivationHeaders.ui_headers_4))
			.exec(http("ui_request_199")
				.get(Common.uri_ui + "/assets/img/cloader.gif"))
			.exec(http("ui_request_200")
				.get(Common.uri_ui + "/config.json")
				.headers(VerizonNewActivationHeaders.ui_headers_16))
			.exec(http("dsom_request_201")
				.options(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.dsom_headers_222))
			.exec(http("dsom_request_202")
				.options(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.dsom_headers_1))
			.exec(http("dsom_request_204")
				.options(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_70))
			.exec(http("dsom_request_205")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/ActivationsWithInsurance_0205_request.json")))
			.exec(http("dsom_request_206")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/ActivationsWithInsurance_0206_request.json")))
			.exec(http("dsom_request_207")
				.post(Common.uri_dsom_v1_port + "/getContentForAisle")
				.headers(VerizonNewActivationHeaders.ui_headers_72)
				.body(ElFileBody("Verizon/NewActivationE2E/ActivationsWithInsurance_0207_request.json")))
			.pause(1)
			.exec(http("ui_request_208")
				.get(Common.uri_ui + "/app/pages/frame/header/header.html")
				.headers(VerizonNewActivationHeaders.ui_headers_208)
				.resources(http("ui_request_209")
					.get(Common.uri_ui + "/app/pages/frame/footer/footer.html")
					.headers(VerizonNewActivationHeaders.ui_headers_208),
					http("ui_request_210")
						.get(Common.uri_ui + "/app/pages/addonpayment/addonpayment.html")
						.headers(VerizonNewActivationHeaders.ui_headers_16),
					http("ui_request_211")
						.get(Common.uri_ui + "/assets/img/bullseye.svg"),
					http("ui_request_212")
						.get("/img/brands/target/retail/EMV-machine.png")
						.headers(VerizonNewActivationHeaders.poa_headers_37)))
			.exec(http("dsom_request_213")
				.options(Common.uri_dsom_v1_port + "/order/${p_orderid}/payment")
				.headers(VerizonNewActivationHeaders.poa_headers_175)
				.resources(http("dsom_request_214")
					.post(Common.uri_dsom_v1_port + "/order/${p_orderid}/payment")
					.headers(VerizonNewActivationHeaders.dsom_headers_20)
					.body(ElFileBody("Verizon/NewActivationE2E/ActivationsWithInsurance_0214_request.json"))
					.check(headerRegex("Set-Cookie","paymentId=(.*); path=/").saveAs("p_paymentid"))))
			.pause(1)
			.exec(http("pam_request_asyncpayment")
				.post(Common.uri_pam + "/PAM/api/pam/v1/payment/asyncpayment")
				.headers(VerizonNewActivationHeaders.pam_headers_02)
				.body(ElFileBody("Verizon/NewActivationE2E/async_payment_request.json"))
				.check(status.is(200)))
			.exec(http("dsom_pay_request_215")
				.options(Common.uri_dsom_v1_port + "/order/${p_orderid}/payment/${p_paymentId}")
				.headers(VerizonNewActivationHeaders.dsom_headers_19))
			.exec(http("dsom_pay_request_216")
				.get(Common.uri_dsom_v1_port + "/order/${p_orderid}/payment/${p_paymentId}")
				.headers(VerizonNewActivationHeaders.dsom_headers_20)
				.check(status.is(200)))

	}
}